// Generated by CoffeeScript 1.7.1
(function() {
  App.SelectorListComponent = Ember.Component.extend({
    currentIndex: 0,
    currentModel: (function() {
      return this.get('models')[this.get('currentIndex')];
    }).property('currentIndex'),
    indexDidChange: (function() {
      this.sendAction('indexUpdate', this.get('currentIndex'));
      return this.sendAction('modelUpdate', this.get('currentModel'));
    }).observes('currentIndex').on('init')
  });

  App.SelectorListItemComponent = Ember.Component.extend({
    classNameBindings: ['selected'],
    classNames: ['selector-item'],
    selected: (function() {
      return this.get('list.currentIndex') === this.get('index');
    }).property('list.currentIndex'),
    click: function() {
      return this.get('list').set('currentIndex', this.get('index'));
    }
  });

}).call(this);
