// Generated by CoffeeScript 1.7.1
(function() {
  window.App = Ember.Application.create({
    LOG_TRANSITIONS: true
  });

  App.Router.map(function() {
    this.route("about", {
      path: "/about"
    });
    return this.route("favorites", {
      path: "/favs"
    });
  });

  App.IndexRoute = Ember.Route.extend({
    model: function(params) {
      return {
        addresses: [
          {
            line1: 'foo',
            line2: 'quuux'
          }, {
            line1: 'bar',
            line2: 'qux'
          }
        ]
      };
    }
  });

  App.IndexController = Ember.ObjectController.extend({
    actions: {
      updateAddress: function(address) {
        return this.set('currentAddress', address);
      }
    }
  });

  App.AddressSelectView = Ember.View.extend({
    templateName: 'address-select',
    classNames: ['address-select']
  });

  App.AddressView = Ember.View.extend({
    templateName: 'address'
  });

  App.SelectorListComponent = Ember.Component.extend({
    currentIndex: 0,
    currentModel: (function() {
      return this.get('models')[this.get('currentIndex')];
    }).property('currentIndex'),
    indexDidChange: (function() {
      this.sendAction('indexUpdate', this.get('currentIndex'));
      return this.sendAction('modelUpdate', this.get('currentModel'));
    }).observes('currentIndex').on('init')
  });

  App.SelectorListItemComponent = Ember.Component.extend({
    classNameBindings: ['selected'],
    classNames: ['selector-item'],
    selected: (function() {
      return this.get('list.currentIndex') === this.get('index');
    }).property('list.currentIndex'),
    click: function() {
      return this.get('list').set('currentIndex', this.get('index'));
    }
  });

}).call(this);
